module.exports = {
  // Auth
  EMAIL_REQUIRED:                    'Email is required',
  EMAIL_INVALID:                     'Please provide a valid email',
  PASSWORD_REQUIRED:                 'Password is required',
  PASSWORD_MIN:                      'Password must be at least 8 characters',
  PASSWORD_PATTERN:                  'Password must contain uppercase, lowercase and a number',
  NAME_REQUIRED:                     'Name is required',
  NAME_MIN:                          'Name must be at least 3 characters',
  NAME_MAX:                          'Name must not exceed 50 characters',
  UNAUTHORIZED:                      'Unauthorized access',
  TOKEN_INVALID:                     'Token is invalid or expired',
  API_KEY_REQUIRED:                  'API key is required',
  API_KEY_INVALID:                   'Invalid API key',
  PLAN_LIMIT_REACHED:                'Free plan limit reached. Please upgrade.',
  EMAIL_ALREADY_EXISTS:              'Email is already registered',
  INVALID_CREDENTIALS:               'Invalid email or password',
  IP_RATE_LIMIT_EXCEEDED:            'Too many requests from this IP.',
  API_KEY_REGENERATE_LIMIT_EXCEEDED: 'API key can only be regenerated 3 times per day.',
  PDF_LIMIT_EXCEEDED:                'PDF generation limit reached. Please upgrade.',
  EMAIL_LIMIT_EXCEEDED:              'Email limit reached. Max 20 emails per hour.',
  RATE_LIMIT_EXCEEDED:               'Too many requests. Please slow down.',
  AUTH_RATE_LIMIT_EXCEEDED:          'Too many attempts. Please try again after 1 minute.',
  TOKEN_BLACKLISTED:                 'Token has been invalidated. Please login again.',
  ACCOUNT_LOCKED:                    'Account locked. Try again after 15 minutes.',
  REFRESH_TOKEN_REQUIRED:            'Refresh token is required.',
  REFRESH_TOKEN_INVALID:             'Invalid or expired refresh token.',
  LOGOUT_SUCCESS:                    'Logged out successfully.',

  // Invoice
  CLIENT_NAME_REQUIRED:              'Client name is required',
  CLIENT_EMAIL_REQUIRED:             'Client email is required',
  CLIENT_EMAIL_INVALID:              'Please provide a valid client email',
  ITEMS_REQUIRED:                    'At least one item is required',
  ITEM_DESC_REQUIRED:                'Item description is required',
  ITEM_QTY_REQUIRED:                 'Item quantity is required',
  ITEM_RATE_REQUIRED:                'Item rate is required',
  CURRENCY_INVALID:                  'Invalid currency code',
  ITEM_AMOUNT_REQUIRED:              'Item amount is required',
  INVOICE_NOT_FOUND:                 'Invoice not found',
  INVOICE_NOT_EDITABLE:              'Only draft invoices can be edited',
  INVOICE_PAID_DELETE:               'Paid invoices cannot be deleted',
  INVOICE_ALREADY_PAID:              'Invoice is already marked as paid',
  INVOICE_DELETED:                   'Invoice deleted successfully',
  INVOICE_SENT:                      'Invoice queued for sending successfully',
  GOOGLE_AUTH_FAILED:                'Google authentication failed. Please try again.',
  FORBIDDEN:                         'You do not have permission to perform this action',
  USER_NOT_FOUND:                    'User not found',
  USER_ACTIVATED:                    'User activated successfully',
  USER_BANNED:                       'User banned successfully',
  PLAN_UPDATED:                      'Plan updated successfully',
 
  //status code
  OK:                      200,
  CREATED:                 201,
  BAD_REQUEST:             400,
  UNAUTHORIZED_CODE:       401,
  FORBIDDEN_CODE:          403,
  NOT_FOUND_CODE:               404,
  CONFLICT:                409,
  SERVER_ERROR:            500,
  TOO_MANY_REQUESTS:       429,
};